apiVersion: v1
kind: Service
metadata:
  name: db-mysql-service
  labels:
    name: db-mysql
    app: srv-db-mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    name: db-mysql
    app: srv-db-mysql
  type: NodePort