apiVersion: v1
kind: Secret
metadata:
  name: mysql-dbs-urls-secret
type: Opaque
stringData:
  ms_productos_db_url: jdbc:mysql://db-mysql-service:3306/db_ms_productos?createDatabaseIfNotExist=true&useSSL=true
  ms_clientes_db_url: jdbc:mysql://db-mysql-service:3306/db_ms_clientes?createDatabaseIfNotExist=true&useSSL=true
  ms_vendedores_db_url: jdbc:mysql://db-mysql-service:3306/db_ms_vendedores?createDatabaseIfNotExist=true&useSSL=true
  ms_pedidos_db_url: jdbc:mysql://db-mysql-service:3306/db_ms_pedidos?createDatabaseIfNotExist=true&useSSL=true
  ms_pagos_db_url: jdbc:mysql://db-mysql-service:3306/db_ms_pagos?createDatabaseIfNotExist=true&useSSL=true